In [1]:
import pandas as pd
import os

# path to the folder where the tables (CSV files) are located
folder_path = 'grb_csv/processed/processed_3sec'

# get the list of all CSV files in the folder
csv_files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]

# create an empty list to store the tables
dataframes = []

# load each CSV file into a DataFrame and add it to the list
for file in csv_files:
    file_path = os.path.join(folder_path, file)
    df = pd.read_csv(file_path)
    dataframes.append(df)
# combine all DataFrames into one

mega_df = pd.concat(dataframes, ignore_index=True)


# save the combined table to a file
output_file = '3sec_table.csv'
mega_df.to_csv(output_file, index=False)
print(mega_df.info())
print(mega_df.describe())

print(f"saved the combined table to a file:: {output_file}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 648000 entries, 0 to 647999
Data columns (total 21 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   NWC (Australia)          648000 non-null  float64
 1   NAA (USA)                648000 non-null  float64
 2   NRK (Iceland)            648000 non-null  float64
 3   ICV (Italy)              648000 non-null  float64
 4   GQD (UK)                 648000 non-null  float64
 5   DHO (Germany)            648000 non-null  float64
 6   Time                     648000 non-null  float64
 7   data                     648000 non-null  object
 8   peak_australia           648000 non-null  int64
 9   peak_usa                 648000 non-null  int64
 10  peak_iceland             648000 non-null  int64
 11  peak_italy               648000 non-null  int64
 12  peak_uk                  648000 non-null  int64
 13  peak_germany             648000 non-null  int64
 14  time_bin                 647946 non-null  object
 15  bin_flag_peak_usa        647946 non-null  float64
 16  bin_flag_peak_germany    647946 non-null  float64
 17  bin_flag_peak_australia  647946 non-null  float64
 18  bin_flag_peak_italy      647946 non-null  float64
 19  bin_flag_peak_iceland    647946 non-null  float64
 20  bin_flag_peak_uk         647946 non-null  float64
dtypes: float64(13), int64(6), object(2)
memory usage: 103.8+ MB
None
       NWC (Australia)      NAA (USA)  NRK (Iceland)    ICV (Italy)  \
count    648000.000000  648000.000000  648000.000000  648000.000000
mean         11.215983      11.945832       6.292245      17.213970
std           4.519123       4.864317       4.728236       5.754497
min          -5.795020      -6.596930     -10.342800      -6.124560
25%           8.860650       8.373548       3.009090      14.865300
50%          11.284700      12.432100       5.834830      17.988800
75%          13.267500      15.958500       8.823552      20.645800
max          42.123100      36.005400      37.074300      39.012900

            GQD (UK)  DHO (Germany)           Time  peak_australia  \
count  648000.000000  648000.000000  648000.000000   648000.000000
mean       14.951251      26.479652     120.010000        0.000318
std         5.545437       7.533709      69.282086        0.017827
min        -7.355060      -6.310360       0.020000        0.000000
25%        11.763100      25.304900      60.015000        0.000000
50%        15.423400      29.058600     120.010000        0.000000
75%        19.069625      31.773900     180.005000        0.000000
max        41.286900      39.388400     240.000000        1.000000

            peak_usa  peak_iceland     peak_italy        peak_uk  \
count  648000.000000  648000.00000  648000.000000  648000.000000
mean        0.000398       0.00038       0.000278       0.000534
std         0.019950       0.01948       0.016664       0.023101
min         0.000000       0.00000       0.000000       0.000000
25%         0.000000       0.00000       0.000000       0.000000
50%         0.000000       0.00000       0.000000       0.000000
75%         0.000000       0.00000       0.000000       0.000000
max         1.000000       1.00000       1.000000       1.000000

        peak_germany  bin_flag_peak_usa  bin_flag_peak_germany  \
count  648000.000000      647946.000000          647946.000000
mean        0.000233           0.080244               0.047842
std         0.015263           0.271671               0.213432
min         0.000000           0.000000               0.000000
25%         0.000000           0.000000               0.000000
50%         0.000000           0.000000               0.000000
75%         0.000000           0.000000               0.000000
max         1.000000           1.000000               1.000000

       bin_flag_peak_australia  bin_flag_peak_italy  bin_flag_peak_iceland  \
count            647946.000000        647946.000000          647946.000000
mean                  0.055556             0.052085               0.066359
std                   0.229062             0.222198               0.248909
min                   0.000000             0.000000               0.000000
25%                   0.000000             0.000000               0.000000
50%                   0.000000             0.000000               0.000000
75%                   0.000000             0.000000               0.000000
max                   1.000000             1.000000               1.000000

       bin_flag_peak_uk
count     647946.000000
mean           0.097612
std            0.296789
min            0.000000
25%            0.000000
50%            0.000000
75%            0.000000
max            1.000000
Об'єднана таблиця збережена у файл: 3sec_table.csv

Кількість випадків: 54